name: woofcare
description: "An app for stray dogs in need"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.9.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.1
  google_fonts: ^6.2.1
  location: ^7.0.1
  intl: ^0.19.0
  custom_floating_action_button_location: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/patterns/
    - assets/images/placeholders/
    - assets/images/homePageButtons/
