name: woofcare
description: "An app for stray dogs in need"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  font_awesome_flutter: ^10.11.0
  google_maps_flutter: ^2.13.1
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.1
  auto_size_text: ^3.0.0
  google_fonts: ^6.3.2
  url_launcher: ^6.1.7
  location: ^8.0.0
  sizer: ^3.1.3
  intl: ^0.20.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/map/
    - assets/images/patterns/
    - assets/images/chat_icons/
    - assets/images/placeholders/
    - assets/images/homePageButtons/
