name: woofcare
description: "An app for stray dogs in need"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.9.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.1
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  location: ^8.0.0
  intl: ^0.20.2
  get: ^4.6.6
  sizer: ^3.0.5
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/map/
    - assets/images/patterns/
    - assets/images/chat_icons/
    - assets/images/placeholders/
    - assets/images/homePageButtons/
